INSERT INTO exercises (name, category, muscle_group) VALUES
    ('Bench Press', 'Strength', 'Chest'),
    ('Incline Dumbbell Press', 'Strength', 'Chest'),
    ('Chest Fly', 'Strength', 'Chest'),
    ('Squat', 'Strength', 'Legs'),
    ('Leg Press', 'Strength', 'Legs'),
    ('Leg Extension', 'Strength', 'Legs'),
    ('Leg Curl', 'Strength', 'Legs'),
    ('Deadlift', 'Strength', 'Back'),
    ('Pull-ups', 'Strength', 'Back'),
    ('Lat Pulldown', 'Strength', 'Back'),
    ('Seated Cable Row', 'Strength', 'Back'),
    ('Shoulder Press', 'Strength', 'Shoulders'),
    ('Lateral Raise', 'Strength', 'Shoulders'),
    ('Front Raise', 'Strength', 'Shoulders'),
    ('Bicep Curl', 'Strength', 'Biceps'),
    ('Tricep Pushdown', 'Strength', 'Triceps'),
    ('Plank', 'Core', 'Abs'),
    ('Russian Twist', 'Core', 'Abs'),
    ('Leg Raise', 'Core', 'Abs'),
    ('Running', 'Cardio', 'Legs'),
    ('Cycling', 'Cardio', 'Legs'),
    ('Swimming', 'Cardio', 'Full Body'),
    ('Rowing', 'Cardio', 'Full Body');